In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_parquet("data/games_2024_2025_2026.parquet")

# todays_games = df[df["game_date"] == "2026-04-08"]

home_favored = df[
    (df["sp_kbb_diff"] > 3) &
    (df["sp_xfip_diff"] < -0.5) &
    (df["offense_diff"] > 10)
]

away_favored = df[
    (df["sp_kbb_diff"] < -3) &
    (df["sp_xfip_diff"] > 0.5) &
    (df["offense_diff"] < -10)
]

mismatches = pd.concat([home_favored, away_favored])
# mismatches["favored_team"] = mismatches.apply(
#     lambda row: row["home_team_name"] if row["sp_kbb_diff"] > 0 else row["away_team_name"],
#     axis=1
# )

mismatches["favored_home"] = mismatches["sp_kbb_diff"] > 0
mismatches["favored_won"] = (
    (mismatches["favored_home"] & (mismatches["home_win"] == 1)) |
    (~mismatches["favored_home"] & (mismatches["home_win"] == 0))
)

mismatches["game_date"] = pd.to_datetime(mismatches["game_date"])

mismatches["year"] = mismatches["game_date"].dt.year
mismatches["month"] = mismatches["game_date"].dt.month

mismatches[~mismatches["favored_home"]].tail(5)

,game_pk,game_date,detailed_state,home_team_name,away_team_name,home_score,away_score,home_probable_pitcher,away_probable_pitcher,home_wrc_plus,away_wrc_plus,home_sp_kbb,away_sp_kbb,home_sp_xfip,away_sp_xfip,home_win,sp_kbb_diff,sp_xfip_diff,offense_diff,stats_season,favored_home,favored_won,year,month
5988,824783,2026-04-06,Final,Boston Red Sox,Milwaukee Brewers,6.0,8.0,Brayan Bello,Brandon Woodruff,96.689895,110.191638,0.000000,17.391304,5.600000,4.506250,0.0,-17.391304,1.093750,-13.501742,2026,False,True,2026,4
5993,824376,2026-04-06,Final,Colorado Rockies,Houston Astros,9.0,7.0,Ryan Feltner,Cody Bolton,97.560976,122.822300,5.714286,23.333333,4.540000,3.372727,1.0,-17.619048,1.167273,-25.261324,2026,False,False,2026,4
5995,823237,2026-04-06,Final,San Francisco Giants,Philadelphia Phillies,4.0,6.0,Adrian Houser,Andrew Painter,87.833914,99.012776,7.547170,16.666667,2.658824,1.814286,0.0,-9.119497,0.844538,-11.178862,2026,False,True,2026,4
6010,823235,2026-04-07,Final,San Francisco Giants,Philadelphia Phillies,6.0,0.0,Robbie Ray,Cristopher Sánchez,87.833914,99.012776,17.391304,27.536232,3.561538,1.018367,1.0,-10.144928,2.543171,-11.178862,2026,False,False,2026,4
6018,823234,2026-04-08,In Progress,San Francisco Giants,Philadelphia Phillies,0.0,0.0,Tyler Mahle,Aaron Nola,87.833914,99.012776,17.777778,27.659574,4.400000,3.364706,NaN,-9.881797,1.035294,-11.178862,2026,False,False,2026,4

In [4]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_parquet("data/games_2024_2025_2026.parquet")

todays_games = df[df["game_date"] == "2026-04-09"]

todays_games.tail(25)

,game_pk,game_date,detailed_state,home_team_name,away_team_name,home_score,away_score,home_probable_pitcher,away_probable_pitcher,home_wrc_plus,away_wrc_plus,home_sp_kbb,away_sp_kbb,home_sp_xfip,away_sp_xfip,home_win,sp_kbb_diff,sp_xfip_diff,offense_diff,stats_season
6026,823884,2026-04-09,Scheduled,Miami Marlins,Cincinnati Reds,NaN,NaN,Max Meyer,Rhett Lowder,105.981417,88.559814,13.636364,11.627907,3.720690,3.736364,NaN,2.008457,-0.015674,17.421603,2026
6027,823565,2026-04-09,Scheduled,New York Yankees,Athletics,NaN,NaN,Ryan Weathers,Jeffrey Springs,104.239257,95.383275,15.789474,11.627907,2.225000,2.570588,NaN,4.161567,-0.345588,8.855981,2026
6028,823724,2026-04-09,Scheduled,Minnesota Twins,Detroit Tigers,NaN,NaN,Mick Abel,Jack Flaherty,95.673635,99.448316,0.000000,0.000000,4.872727,5.140000,NaN,0.000000,-0.267273,-3.774681,2026
6029,823645,2026-04-09,Scheduled,New York Mets,Arizona Diamondbacks,NaN,NaN,Nolan McLean,Eduardo Rodriguez,103.077816,91.608595,19.512195,10.869565,3.487097,2.516667,NaN,8.642630,0.970430,11.469222,2026
6030,824130,2026-04-09,Scheduled,Kansas City Royals,Chicago White Sox,NaN,NaN,Seth Lugo,Anthony Kay,99.303136,90.011614,17.777778,-2.500000,1.864706,6.877778,NaN,20.277778,-5.013072,9.291521,2026